### PR TITLE
fix(resolve): resolve constructs with child objects that reference instances of classes

### PR DESCRIPTION
**Pull request by heckler1**
Hopefully the test cases here explain my intent more clearly, but we need to resolve where the values are instances of classes that can be parsed to strings. This behavior was working until the recent refactor. 

I believe this change is the least-obtrusive option to retain backward compatibility, as it just re-adds the gate that was originally in the resolve function. But, I'm open to any feedback or improvements you'd like to see here.

### CODE REVIEW

**Comment by heckler1** [comment]
@iliapolo If you wouldn't mind taking a look 🙏

**Comment by iliapolo** [comment]
@heckler1 This is interesting. Honestly, i'm not sure we ever intended for the cases you test here to actually work. They might have just been a side-effect of the implementation. 

Im good merging this to preserve backwards compatibility, but do you actually have real use-cases for them?

**Comment by heckler1** [comment]
Thanks for taking a look, I agree this definitely was undefined behavior before, but yes, the usecase I'm trying to fix here is one we are actively using. 

I created a gist with a minimal repro of what we're doing for clarity, but the long-story-short here is that we have clusters with differing API versions, and so need to create either Ingress v1 or Ingress v1beta1 based on destination cluster. We've implemented a compatibility Construct that leverages the existing Ingress props to maintain the k8s API interface for users, but added a "Cluster" field we can use to check API version and determine which Ingress version to create.
At synth time the `cluster` field is part of the props of the construct and so, even though the construct is not actually rendered in the output, it's still resolved as part of recursive resolution through the chain of constructs. 

Another use case that is in our codebase, but easier to fix in other ways since it's not user-facing, is referencing a field that contains one of these classes, and relying on the implicit stringification of that instance. Such as `mydomain.${props.cluster}.example.com`

https://gist.github.com/heckler1/cd5487fc10d166b256a4d240e6d63b94

**Comment by iliapolo** [comment]
@heckler1 So with respect to the gist you linked to, wouldn't it make more sense to remove the `cluster` property from `props` before passing it down to the underlying construct?

```ts
if (useV1Beta1) {
  delete props.cluster // or clone and delete...
  this.newV1Beta1(id, props);
} 
```

Is this not an option? Presumably any wrapper you write knows which properties shouldn't take part in the resolution process and shouldn't be passed in inside props. In the test you mentioned that you allow arbitrary props, how so? a user can pass in whatever they want even though its not part of the schema?

**Comment by heckler1** [comment]
@iliapolo I don't believe the props as passed down to the child KubeIngress APIObjects/Constructs is the issue, it seems to be the actual props argument as passed to the constructor of the `Ingress extends Construct` class. (https://gist.github.com/heckler1/cd5487fc10d166b256a4d240e6d63b94#file-ingress_compat-ts-L29)

I did test cloning the props and enforcing that the types are properly restricted to the upstream API schemas but with no change, again because I believe it has to do with the resolution of the parent construct, not the child API objects

I believe because the resolution is happening recursively, even though the it's not rendered out as YAML, the Ingress construct is still resolved. The only fix I was able to find in our internal code that mimics the gist was to change the `cluster: Cluster` field to `clusterAPIVersion: string`, as the resolver knows what to do with strings. Unfortunately though this would break all user code that references this. (https://gist.github.com/heckler1/cd5487fc10d166b256a4d240e6d63b94#file-ingress_compat-ts-L20)

We don't allow arbitrary props as part of the schemas as passed to the actual K8S API Object constructors. E.g. `new KubeIngress` is going to have `KubeIngressProps` passed to it as you'd expect. The only arbitrary props are passed into the constructor for the custom construct.

**Comment by iliapolo** [comment]
@heckler1 Something still doesn't add up...the [line](https://gist.github.com/heckler1/cd5487fc10d166b256a4d240e6d63b94#file-ingress_compat-ts-L29) here doesn't do anything by itself because 1) you're not supering the props, and 2) only `ApiObject` instances participate in the resolution, not every `Construct`.

https://github.com/cdk8s-team/cdk8s-core/blob/6a2645835098ac5d85b6192aeae4cae68c2ea9eb/src/app.ts#L372-L376

I pinged you on slack BTW if you want to catch up online :)

**Comment by heckler1** [comment]
Per discussion in slack: Due to the union type shown in the gist, the props as passed to the KubeIngress constructor actually contain an implicit `cluster` field that then cdk8s attempts to synth, causing errors. Even when explicitly cloning and casting to KubeIngressProps, the cluster field rides along inside the JS object.

By doing `delete (props as any).cluster`, we can prevent the implicit field from being passed along into the KubeIngress constructor, subsequently being `super`'d, and then causing synth failures due to unexpected fields

**Pull request closed without merging**
